In [54]:
import numpy as np
import pandas as pd

In [55]:
#1. Create a Series of 5 student names.
name = pd.Series(['s1','s2','s3','s4','s5'])
name

0    s1
1    s2
2    s3
3    s4
4    s5
dtype: object

In [56]:
#2. Create a Series of 5 marks and display it.
marks = pd.Series([34,50,59,39,43])
marks

0    34
1    50
2    59
3    39
4    43
dtype: int64

In [57]:
# 3. Create a Series with custom index labels like A, B, C, D.
label=['A','B','C','D','E']
data=[1,2,3,4,5]
custom_index=pd.Series(data,index=label)
custom_index

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [58]:
marks.index=['A','B','C','D','E']

In [59]:
#4. Access the third value from a Series.
marks.iloc[2]

59

In [60]:
#5. Access a value from a Series using its custom label.
marks.loc['A']

34

In [61]:
#6. Change one value in a Series.
marks['A']=99
marks

A    99
B    50
C    59
D    39
E    43
dtype: int64

In [62]:
#7. Add 10 to every value in a numeric Series.
marks +10

A    109
B     60
C     69
D     49
E     53
dtype: int64

In [63]:
#8. Find the maximum value in a Series.
marks.max()

99

In [64]:
#9. Find the minimum value in a Series.
marks.min()

39

In [65]:
#10. Find the mean of a numeric Series.
marks.mean()

58.0

In [66]:
#11. Filter only values greater than 50 in a Series.
marks[marks>50]

A    99
C    59
dtype: int64

In [67]:
#12. Create a Series from a dictionary.
dict1={1:'P',2:'R',3:'A',4:'N',5:'A',6:'V'}
s1=pd.Series(dict1)
s1

1    P
2    R
3    A
4    N
5    A
6    V
dtype: object

In [68]:
# 13. Check the index of a Series.
marks.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [69]:
#14. Check the values of a Series.
marks.values

array([99, 50, 59, 39, 43], dtype=int64)

In [70]:
#Convert a Series into a list.
l1=list(marks)
l1

[99, 50, 59, 39, 43]

In [71]:
l2=marks.tolist()
l2

[99, 50, 59, 39, 43]

In [72]:
#16. Check which values in a Series are null.
s1=pd.Series([1,2,3,np.nan])
s1[s1.isna()==True]

3   NaN
dtype: float64

In [73]:
s1[s1.isnull()==True]

3   NaN
dtype: float64

In [74]:
#17. Fill missing values in a Series with 0.
s1.fillna(0,inplace=True)
s1

0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64

In [75]:
#18. Count how many times each value appears in a Series.
s2=pd.Series([11,223,1,1,1,44,44,56,23,78,54,78])
s2.value_counts()

1      3
44     2
78     2
11     1
223    1
56     1
23     1
54     1
Name: count, dtype: int64

In [76]:
#19. Sort a Series by values.
s2.sort_values(ascending=True)

2       1
3       1
4       1
0      11
8      23
5      44
6      44
10     54
7      56
9      78
11     78
1     223
dtype: int64

In [77]:
#20. Sort a Series by index.
s2.sort_index()

0      11
1     223
2       1
3       1
4       1
5      44
6      44
7      56
8      23
9      78
10     54
11     78
dtype: int64

In [78]:
#21. Create a DataFrame of 5 students with columns Name, Age, Marks.
data = {
    'Name': ['Pranav', 'Ajinkya','Shubham','Chirayu','Raghav'],
    'Age': [22,23,23,25,21],
    'Marks': [100,90,90,87,86]
}

df = pd.DataFrame(data)
df

      Name  Age  Marks
0   Pranav   22    100
1  Ajinkya   23     90
2  Shubham   23     90
3  Chirayu   25     87
4   Raghav   21     86

In [79]:
#22. Display the first 3 rows of a DataFrame.
df.head(3)

      Name  Age  Marks
0   Pranav   22    100
1  Ajinkya   23     90
2  Shubham   23     90

In [80]:
#23. Display the last 2 rows of a DataFrame.
df.tail(2)

      Name  Age  Marks
3  Chirayu   25     87
4   Raghav   21     86

In [81]:
#24. Display only one column from a DataFrame.
df['Name']

0     Pranav
1    Ajinkya
2    Shubham
3    Chirayu
4     Raghav
Name: Name, dtype: object

In [82]:
#25. Display two columns from a DataFrame.
df[['Name','Age']]

      Name  Age
0   Pranav   22
1  Ajinkya   23
2  Shubham   23
3  Chirayu   25
4   Raghav   21

In [83]:
#26. Add a new column called Passed based on Marks > 40.
df['Passed']=df['Marks']>40
df
#df['Passed'] = df['Marks'].apply(lambda x: 'Yes' if x > 40 else 'No')

      Name  Age  Marks  Passed
0   Pranav   22    100    True
1  Ajinkya   23     90    True
2  Shubham   23     90    True
3  Chirayu   25     87    True
4   Raghav   21     86    True

In [84]:
#27. Add a new column called Bonus with fixed value 5.
df['Bonus']=5
df

      Name  Age  Marks  Passed  Bonus
0   Pranav   22    100    True      5
1  Ajinkya   23     90    True      5
2  Shubham   23     90    True      5
3  Chirayu   25     87    True      5
4   Raghav   21     86    True      5

In [85]:
#28. Change the values of one existing column.
df['Marks']=[100,88,99,56,53]
df

      Name  Age  Marks  Passed  Bonus
0   Pranav   22    100    True      5
1  Ajinkya   23     88    True      5
2  Shubham   23     99    True      5
3  Chirayu   25     56    True      5
4   Raghav   21     53    True      5

In [86]:
#29. Delete one column from a DataFrame.
df.drop(columns='Bonus',inplace=True)
df

      Name  Age  Marks  Passed
0   Pranav   22    100    True
1  Ajinkya   23     88    True
2  Shubham   23     99    True
3  Chirayu   25     56    True
4   Raghav   21     53    True

In [87]:
#30. Rename a column in a DataFrame.
df.rename(columns={'Passed':'Pass'})

      Name  Age  Marks  Pass
0   Pranav   22    100  True
1  Ajinkya   23     88  True
2  Shubham   23     99  True
3  Chirayu   25     56  True
4   Raghav   21     53  True

In [88]:
#31. Set Name as index of the DataFrame.
df_custom_index=df.set_index('Name')
df_custom_index

         Age  Marks  Passed
Name
Pranav    22    100    True
Ajinkya   23     88    True
Shubham   23     99    True
Chirayu   25     56    True
Raghav    21     53    True

In [89]:
# 32. Reset the index back to default integers.
df_custom_index=df_custom_index.reset_index()
df_custom_index

      Name  Age  Marks  Passed
0   Pranav   22    100    True
1  Ajinkya   23     88    True
2  Shubham   23     99    True
3  Chirayu   25     56    True
4   Raghav   21     53    True

In [90]:
#33. Select the first row using iloc.
df.iloc[0]

Name      Pranav
Age           22
Marks        100
Passed      True
Name: 0, dtype: object

In [91]:
#34. Select a row using loc with label index.
df.set_index('Name',inplace=True)
df.loc['Pranav']

Age         22
Marks      100
Passed    True
Name: Pranav, dtype: object

In [92]:
#35. Filter students with Marks greater than 60.
df[df.Marks>60]

         Age  Marks  Passed
Name
Pranav    22    100    True
Ajinkya   23     88    True
Shubham   23     99    True

In [93]:
#36. Filter students whose Age is less than 20.
df[df.Age<20]

Empty DataFrame
Columns: [Age, Marks, Passed]
Index: []

In [94]:
#37. Find the average Marks of all students.
df['Marks'].mean()

79.2

In [95]:
#38. Find the student with highest Marks.
df['Marks'].max()

100

In [97]:
#39. Sort the DataFrame by Marks in ascending order.
df.sort_values(by='Marks')

         Age  Marks  Passed
Name
Raghav    21     53    True
Chirayu   25     56    True
Ajinkya   23     88    True
Shubham   23     99    True
Pranav    22    100    True

In [99]:
#40. Sort the DataFrame by Age in descending order.
df.sort_values(by='Age')

         Age  Marks  Passed
Name
Raghav    21     53    True
Pranav    22    100    True
Ajinkya   23     88    True
Shubham   23     99    True
Chirayu   25     56    True

In [101]:
#41. Check DataFrame shape.
df.shape

(5, 3)

In [102]:
# 42. Check DataFrame column names.
df.columns

Index(['Age', 'Marks', 'Passed'], dtype='object')

In [108]:
#43. Check DataFrame data types.
df.dtypes

Age       int64
Marks     int64
Passed     bool
dtype: object

In [113]:
#44. Check if any values are missing in the DataFrame.
df.isnull().values.any()

False

In [117]:
# 45. Fill missing values in Marks with the column mean.
df['Marks'].fillna(df['Marks'].mean())

Name
Pranav     100
Ajinkya     88
Shubham     99
Chirayu     56
Raghav      53
Name: Marks, dtype: int64

In [118]:
# 46. Drop rows containing missing values.
df.dropna()

         Age  Marks  Passed
Name
Pranav    22    100    True
Ajinkya   23     88    True
Shubham   23     99    True
Chirayu   25     56    True
Raghav    21     53    True

In [119]:
# 47. Count unique values in a column.
df['Age'].unique()

array([22, 23, 25, 21], dtype=int64)

In [120]:
# 48. Find value counts of a categorical column like Department.
df['Passed'].value_counts()

Passed
True    5
Name: count, dtype: int64

In [125]:
# 49. Create a second DataFrame and concatenate it with the first one.
data = {
    'Name': ['Dev', 'rudra','nayan','ashish','vijay'],
    'Age': [22,23,23,25,21],
    'Marks': [100,90,90,76,86]
}
new_studs=pd.DataFrame(data)
new_studs

pd.concat([df,new_studs],ignore_index=True)

   Age  Marks Passed    Name
0   22    100   True     NaN
1   23     88   True     NaN
2   23     99   True     NaN
3   25     56   True     NaN
4   21     53   True     NaN
5   22    100    NaN     Dev
6   23     90    NaN   rudra
7   23     90    NaN   nayan
8   25     76    NaN  ashish
9   21     86    NaN   vijay

In [127]:
# 50. Create two DataFrames with a common column and merge them.
data = {
    'Name': ['Dev', 'rudra','nayan','ashish','vijay'],
    'roll': [21,22,23,24,25],
}
records = {
    'roll': [21,22,23,24,25],
    'Marks': [100,90,90,76,86]
}

students=pd.DataFrame(data)
marks=pd.DataFrame(records)
merged_df = pd.merge(students, marks, on='roll')
merged_df

     Name  roll  Marks
0     Dev    21    100
1   rudra    22     90
2   nayan    23     90
3  ashish    24     76
4   vijay    25     86