In [2]:
import numpy as np
import pandas as pd

In [3]:
# Numpy arrays
company = np.array(['TCS','Infosys','Wipro'])
sales = np.array([100,200,300])
profit = np.array([20,50,70])
# Access profit for TCS
print('Company: ',company)
print('Sales: ',sales)
print('Profit: ',profit)

#accessing elements 
print("Numpy Array")
print("Infosys sales:",sales[1])
print("Infosys profit:",profit[1])

Company:  ['TCS' 'Infosys' 'Wipro']
Sales:  [100 200 300]
Profit:  [20 50 70]
Numpy Array
Infosys sales: 200
Infosys profit: 50

In [4]:
# Pandas series
sales_series=pd.Series(sales,index=company)
profit_series=pd.Series(profit,index=company)
print(sales_series)
print(profit_series)

#accessing using label
print("\naccessing using label\n")
print("Infosys sales:",sales_series['Infosys'])
print("Infosys profit:",profit_series['Infosys'])

TCS        100
Infosys    200
Wipro      300
dtype: int32
TCS        20
Infosys    50
Wipro      70
dtype: int32

accessing using label

Infosys sales: 200
Infosys profit: 50

In [5]:
prn = np.array([8003,8026,8044])
name = np.array(["Ajinkya","Pranav","Shubham"])
mobile = np.array([9898435,998745,125234])
name_series=pd.Series(name,index=prn)
mobile_series=pd.Series(mobile,index=prn)
print("\n Third student name \n")
print("Third student name: name_series[prn[2]] :",name_series[prn[2]])
print("Third student name: name_series[8044] :",name_series[8044])
print("Third student name: name_series.loc[8044] :",name_series.loc[8044])
print("Third student name: name_series.iloc[2] :",name_series.iloc[2])

print("\n second student mobile number \n")
print("Second student mobile: mobile_series[prn[1]] :",mobile_series[prn[1]])
print("Second student mobile: mobile_series[8026] :",mobile_series[8026])
print("Second student mobile: mobile_series.loc[8026] :",mobile_series.loc[8026])
print("Second student mobile: mobile_series.iloc[1] :",mobile_series.iloc[1])

 Third student name

Third student name: name_series[prn[2]] : Shubham
Third student name: name_series[8044] : Shubham
Third student name: name_series.loc[8044] : Shubham
Third student name: name_series.iloc[2] : Shubham

 second student mobile number

Second student mobile: mobile_series[prn[1]] : 998745
Second student mobile: mobile_series[8026] : 998745
Second student mobile: mobile_series.loc[8026] : 998745
Second student mobile: mobile_series.iloc[1] : 998745

In [6]:
# Dataframe
df = pd.DataFrame({
    'Sales': sales,
    'Profit': profit
},index=company)
df

         Sales  Profit
TCS        100      20
Infosys    200      50
Wipro      300      70

In [7]:
# Acess row and multiple column
print('\nUsing Dataframe:')
print(df.loc['Infosys'])
print(df.loc['Infosys',['Sales','Profit']])

Using Dataframe:
Sales     200
Profit     50
Name: Infosys, dtype: int32
Sales     200
Profit     50
Name: Infosys, dtype: int32

In [8]:
# add new column
df['Margin']=df['Profit']/df['Sales']*100
df

         Sales  Profit     Margin
TCS        100      20  20.000000
Infosys    200      50  25.000000
Wipro      300      70  23.333333

In [9]:
# filter multiple column
#print("\nHigh profit companies:\n",df[df['Profit']>40])
df[df['Profit']>40]

         Sales  Profit     Margin
Infosys    200      50  25.000000
Wipro      300      70  23.333333

In [10]:
# combined condition
df[(df['Sales']>150)&(df['Profit']>40)]

         Sales  Profit     Margin
Infosys    200      50  25.000000
Wipro      300      70  23.333333

In [11]:
# Player Dataframe
data={
    'Player':['Rohit','Virat','MS Dhoni'],
    'Match1':[78,69,26],
    'Match2':[67,45,40],
    'Match3':[27,35,60]
}
df = pd.DataFrame(data).set_index('Player')
df

          Match1  Match2  Match3
Player
Rohit         78      67      27
Virat         69      45      35
MS Dhoni      26      40      60

In [12]:
print('By using loc')
print(df.loc['Virat'])
print(df.loc['Virat'].values)

By using loc
Match1    69
Match2    45
Match3    35
Name: Virat, dtype: int64
[69 45 35]

In [13]:
print('By using iloc')
print(df.iloc[1])
print(df.iloc[1].values)

By using iloc
Match1    69
Match2    45
Match3    35
Name: Virat, dtype: int64
[69 45 35]

In [14]:
# moultiple rows
df.loc[['Virat','Rohit']]

        Match1  Match2  Match3
Player
Virat       69      45      35
Rohit       78      67      27

In [15]:
# specific cell
df.loc['Virat','Match1']

69

In [16]:
# slicing
df.iloc[1:3]

          Match1  Match2  Match3
Player
Virat         69      45      35
MS Dhoni      26      40      60

In [17]:
# slicing
df.loc['Rohit':'MS Dhoni']

          Match1  Match2  Match3
Player
Rohit         78      67      27
Virat         69      45      35
MS Dhoni      26      40      60

In [18]:
# subset
print('subset')
df.loc[['Virat','MS Dhoni'],['Match1','Match3']]

subset

          Match1  Match3
Player
Virat         69      35
MS Dhoni      26      60

In [19]:
# sample data
df = pd.DataFrame({
    'Employee':['Pranav','Ajinkya','Shubham','Chirayu','Rudraksh'],
    'Department':['CS','IT','IT','HR','Finace'],
    'Salary':[50000,60000,np.nan,65000,70000]
})
df

   Employee Department   Salary
0    Pranav         CS  50000.0
1   Ajinkya         IT  60000.0
2   Shubham         IT      NaN
3   Chirayu         HR  65000.0
4  Rudraksh     Finace  70000.0

In [20]:
# indexing
df_indexed = df.set_index('Employee')
df_indexed

         Department   Salary
Employee
Pranav           CS  50000.0
Ajinkya          IT  60000.0
Shubham          IT      NaN
Chirayu          HR  65000.0
Rudraksh     Finace  70000.0

In [21]:
# filtering
df[df['Salary']>60000]

   Employee Department   Salary
3   Chirayu         HR  65000.0
4  Rudraksh     Finace  70000.0

In [22]:
# Check missing
df.isnull()

   Employee  Department  Salary
0     False       False   False
1     False       False   False
2     False       False    True
3     False       False   False
4     False       False   False

In [23]:
# Drop missing rows
df.dropna()

   Employee Department   Salary
0    Pranav         CS  50000.0
1   Ajinkya         IT  60000.0
3   Chirayu         HR  65000.0
4  Rudraksh     Finace  70000.0

In [24]:
# Grouping
df.groupby('Department')['Salary'].mean()

Department
CS        50000.0
Finace    70000.0
HR        65000.0
IT        60000.0
Name: Salary, dtype: float64

In [25]:
# merge
df_bonus= pd.DataFrame({
    'Employee':['Ajinkya','Pranav','Chirayu'],
    'Bonus':[5000,7000,4000]
})
pd.merge(df,df_bonus, on='Employee')

  Employee Department   Salary  Bonus
0   Pranav         CS  50000.0   7000
1  Ajinkya         IT  60000.0   5000
2  Chirayu         HR  65000.0   4000

In [29]:
# concat
df_new = pd.DataFrame({
    'Employee':['Rajveer'],
    'Department':['CS'],
    'Salary':[55000]
})
pd.concat([df,df_new])

   Employee Department   Salary
0    Pranav         CS  50000.0
1   Ajinkya         IT  60000.0
2   Shubham         IT      NaN
3   Chirayu         HR  65000.0
4  Rudraksh     Finace  70000.0
0   Rajveer         CS  55000.0